apiVersion: v1
name: jx-pipelines-visualizer
description: Web UI for Jenkins X, with a clear goal - visualize the pipelines - and their logs.
home: https://github.com/dailymotion/jx-pipelines-visualizer
version: 0.0.1 # This gets automatically overridden by our release process
appVersion: latest # This gets automatically overridden by our release process
sources:
- https://github.com/dailymotion/jx-pipelines-visualizer