apiVersion: v1
appVersion: 0.0.46
description: Web UI for Jenkins X, with a clear goal - visualize the pipelines - and their logs.
home: https://github.com/jenkins-x/jx-pipelines-visualizer
name: jx-pipelines-visualizer
sources:
- https://github.com/jenkins-x/jx-pipelines-visualizer
version: 0.0.46
