{{- if .Values.ingress.enabled -}}

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "jxpipelines.fullname" . }}
  labels:
    {{- include "jxpipelines.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{ tpl (toYaml .) $ | trim | indent 4 }}
    {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- tpl (toYaml .) $ | trim | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ tpl . $ }}
    http:
      paths:
      - backend:
          serviceName: {{ include "jxpipelines.fullname" $ }}
          servicePort: http
  {{- end }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
  {{- range $secret := .Values.ingress.tls.secrets }}
  {{- if and $secret.embedded }}
  - secretName: {{ include "jxpipelines.fullname" $ }}-tls-{{ $secret.name }}
  {{- else }}
  - secretName: {{ $secret.name }}
  {{- end }}
    hosts:
{{- range $secret.hosts }}
    - {{ . }}
{{- end }}
  {{- end }}
  {{- end }}

{{- if .Values.ingress.basicAuth.enabled }}
---
apiVersion: v1
data:
  auth: {{ .Values.ingress.basicAuth.authData | quote }}
kind: Secret
metadata:
  name: jx-pipelines-visualizer-basic-auth
type: Opaque
{{- end -}}

{{- if .Values.ingress.tls.enabled -}}
{{- range $secret := .Values.ingress.tls.secrets -}}
{{- if $secret.embedded }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jxpipelines.fullname" $ }}-tls-{{ $secret.name }}
  labels: {{- include "jxpipelines.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $secret.embedded.b64encodedCertificate | quote }}
  tls.key: {{ $secret.embedded.b64encodedCertificateKey | quote }}
{{- end -}}
{{- end -}}
{{- end -}}

{{- end -}}
